export const API_KEY = {
    KEY: 'EvtDfSYhiWaVYZehbhFuZ9skpk66xxXjnewcVtDZ'
}

export const EXAMPLE = [
    {
      collectionCode: "BILLS",
      collectionName: "Congressional Bills",
      granuleCount: null,
      packageCount: 242229,
    },
    {
      collectionCode: "BILLSTATUS",
      collectionName: "Congressional Bill Status",
      granuleCount: null,
      packageCount: 132248,
    },
    {
      collectionCode: "BUDGET",
      collectionName: "United States Budget",
      granuleCount: 6567,
      packageCount: 326,
    },
    {
      collectionCode: "CCAL",
      collectionName: "Congressional Calendars",
      granuleCount: 79012,
      packageCount: 4972,
    },
    {
      collectionCode: "CDIR",
      collectionName: "Congressional Directory",
      granuleCount: 14366,
      packageCount: 21,
    },
    {
      collectionCode: "CDOC",
      collectionName: "Congressional Documents",
      granuleCount: 9203,
      packageCount: 9581,
    },
    {
      collectionCode: "CFR",
      collectionName: "Code of Federal Regulations",
      granuleCount: 6623388,
      packageCount: 5632,
    },
    {
      collectionCode: "CHRG",
      collectionName: "Congressional Hearings",
      granuleCount: 260,
      packageCount: 33563,
    },
    {
      collectionCode: "COMPS",
      collectionName: "Statutes Compilations",
      granuleCount: null,
      packageCount: 2268,
    },
    {
      collectionCode: "CPD",
      collectionName: "Compilation of Presidential Documents",
      granuleCount: 23012,
      packageCount: 13994,
    },
    {
      collectionCode: "CPRT",
      collectionName: "Congressional Committee Prints",
      granuleCount: 1670,
      packageCount: 1673,
    },
    {
      collectionCode: "CREC",
      collectionName: "Congressional Record",
      granuleCount: 725566,
      packageCount: 5168,
    },
    {
      collectionCode: "CRECB",
      collectionName: "Congressional Record (Bound Edition)",
      granuleCount: 451673,
      packageCount: 2400,
    },
    {
      collectionCode: "CRI",
      collectionName: "Congressional Record Index",
      granuleCount: 581187,
      packageCount: 40,
    },
    {
      collectionCode: "CRPT",
      collectionName: "Congressional Reports",
      granuleCount: 525,
      packageCount: 25113,
    },
    {
      collectionCode: "CZIC",
      collectionName: "Coastal Zone Information Center",
      granuleCount: null,
      packageCount: 4888,
    },
    {
      collectionCode: "ECFR",
      collectionName: "Electronic Code of Federal Regulations",
      granuleCount: null,
      packageCount: 49,
    },
    {
      collectionCode: "ECONI",
      collectionName: "Economic Indicators",
      granuleCount: 15691,
      packageCount: 327,
    },
    {
      collectionCode: "ERIC",
      collectionName: "Education Reports from ERIC",
      granuleCount: null,
      packageCount: 573,
    },
    {
      collectionCode: "ERP",
      collectionName: "Economic Report of the President",
      granuleCount: 2738,
      packageCount: 27,
    },
    {
      collectionCode: "FR",
      collectionName: "Federal Register",
      granuleCount: 897721,
      packageCount: 21775,
    },
    {
      collectionCode: "GAOREPORTS",
      collectionName: "Government Accountability Office Reports and Comptroller General Decisions",
      granuleCount: null,
      packageCount: 16569,
    },
    {
      collectionCode: "GOVMAN",
      collectionName: "United States Government Manual",
      granuleCount: 4619,
      packageCount: 26,
    },
    {
      collectionCode: "GOVPUB",
      collectionName: "Bulk Submission",
      granuleCount: 321,
      packageCount: 33566,
    },
    {
      collectionCode: "GPO",
      collectionName: "Additional Government Publications",
      granuleCount: 79862,
      packageCount: 3329,
    },
    {
      collectionCode: "HJOURNAL",
      collectionName: "Journal of the House of Representatives",
      granuleCount: 33948,
      packageCount: 29,
    },
    {
      collectionCode: "HMAN",
      collectionName: "House Rules and Manual",
      granuleCount: 1937,
      packageCount: 14,
    },
    {
      collectionCode: "HOB",
      collectionName: "History of Bills",
      granuleCount: 279275,
      packageCount: 40,
    },
    {
      collectionCode: "LSA",
      collectionName: "List of CFR Sections Affected",
      granuleCount: 16059,
      packageCount: 310,
    },
    {
      collectionCode: "PAI",
      collectionName: "Privacy Act Issuances",
      granuleCount: null,
      packageCount: 1459,
    },
    {
      collectionCode: "PLAW",
      collectionName: "Public and Private Laws",
      granuleCount: null,
      packageCount: 5416,
    },
    {
      collectionCode: "PPP",
      collectionName: "Public Papers of the Presidents of the United States",
      granuleCount: 24847,
      packageCount: 180,
    },
    {
      collectionCode: "SERIALSET",
      collectionName: "Congressional Serial Set",
      granuleCount: null,
      packageCount: 15472,
    },
    {
      collectionCode: "SJOURNAL",
      collectionName: "Journal of the Senate",
      granuleCount: null,
      packageCount: 49,
    },
    {
      collectionCode: "SMAN",
      collectionName: "Senate Manual",
      granuleCount: 1213,
      packageCount: 7,
    },
    {
      collectionCode: "STATUTE",
      collectionName: "Statutes at Large",
      granuleCount: 36109,
      packageCount: 64,
    },
    {
      collectionCode: "USCODE",
      collectionName: "United States Code",
      granuleCount: 1728832,
      packageCount: 1340,
    },
    {
      collectionCode: "USCOURTS",
      collectionName: "United States Courts Opinions",
      granuleCount: 3612694,
      packageCount: 1677602,
    },
  ]