export const TEXT = {
  MAIN_SEARCH_PLACEHOLDER: 'Search',
  CANCEL: 'Cancel',
  GETTING_MAIN_COLLECTIONS: 'Getting main collections...',
  SOMETHING_WENT_WRONG: 'Something went wrong',
  PLEASE_TRY_AGAIN: 'Please try again.\n',
  OKAY: 'Okay',
  DATE_ISSUED: 'Date issued:',
  LAST_MODIFIED: 'Last modified:',
  NO_RESULTS_FOUND: 'No results found',
  GO_BACK: 'Go back',
  YES_VOTE: 'Yes: ',
  NO_VOTE: 'No: ',
  NOT_VOTING_VOTE: 'NV: ',
  PRESENT_VOTE: 'P: ',
  HOUSE: 'House',
  SENATE: 'Senate',
  BOTH: 'Both',
  VOTES: 'Votes',
  HOUSE_AND_SENATE: 'House and Senate',
  GETTING_BOTH_VOTES: 'Getting House and Senate votes...',
  GETTING_HOUSE_VOTES: 'Getting House votes...',
  GETTING_SENATE_VOTES: 'Getting Senate votes...',
  SEARCH_BILLS: 'Search Bills',
  SPONSOR_NAME: 'Sponsor name',
  INTRODUCED_DATE: 'Introduced',
  LAST_MAJOR_ACTION: 'Last major action',
};
